config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :amounts, :users, :recipes, :ingredients
end

app/models/amount.rb
# frozen_string_literal: true

class Amount < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
# frozen_string_literal: true

class Ingredient < ApplicationRecord
  has_many :amounts
  has_many :recipes, through: :amounts
end

app/models/recipe.rb
# frozen_string_literal: true

class Recipe < ApplicationRecord
  belongs_to :user
  has_many :amounts
  has_many :ingredients, through: :amounts
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :recipes
end

app/controllers/amounts_controller.rb
# frozen_string_literal: true

class AmountsController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ingredients_controller.rb
# frozen_string_literal: true

class IngredientsController < ApplicationController

    def index
        @ingredients = Ingredient.all
    end

    def show
        @ingredient = Ingredient.find(params[:id])
    end

end

app/controllers/recipes_controller.rb
# frozen_string_literal: true

class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
    @users = User.all
    @ingredients = Ingredient.all
  end

  def create
    byebug
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      redirect_to recipe_path(@recipe)
    else
      @errors = @recipe.errors.full_messages
      render :new
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :user_id)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def destroy
    User.find(params[:id]).destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipeapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/new.html.erb
<%= form_for @recipe do |f|%>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.collection_select :user_id, @users, :id, :name%>
  <%= f.collection_select(:ingredient_ids, @ingredients, :id, :name, {},  {multiple:true}) %>
  <%= f.submit %>
<% end %>